In [1]:
from sklearn.datasets import load_iris
from FM import FM
from mxnet import nd

## 获取数据

In [2]:
iris = load_iris()

In [3]:
X = nd.array(iris.data[iris.target<=1])
y = nd.array(iris.target[iris.target<=1]).reshape(-1,1)

## 定义模型，初始化模型参数

In [4]:
fm = FM(X.shape[1], 1)

In [5]:
fm.initialize()

In [6]:
fm.params.get('w').data(),fm.params.get('b').data(),fm.params.get('latent_vec').data()

(
 [[0.0068339 ]
  [0.01299825]
  [0.0301265 ]
  [0.04819721]]
 <NDArray 4x1 @cpu(0)>, 
 [[0.01438687]]
 <NDArray 1x1 @cpu(0)>, 
 [[ 0.05011239]
  [ 0.00628365]
  [ 0.04861524]
  [-0.01068833]]
 <NDArray 4x1 @cpu(0)>)

查看次数预测结果

In [7]:
y_hat = fm.predict(X)
sum(y == y_hat)/len(y)


[0.5]
<NDArray 1 @cpu(0)>

In [8]:
fm.train(X, y, max_iter = 10, l1 = 0.1, l2 = 0.1)

1 iter: loss is: 
[0.2893535]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.38635582]
<NDArray 1 @cpu(0)>
2 iter: loss is: 
[0.23570988]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.05364361]
<NDArray 1 @cpu(0)>
3 iter: loss is: 
[0.23306307]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.0026468]
<NDArray 1 @cpu(0)>
4 iter: loss is: 
[0.23439975]
<NDArray 1 @cpu(0)> loss reduction is: 
[-0.00133668]
<NDArray 1 @cpu(0)>


In [9]:
fm.params.get('w').data(),fm.params.get('b').data(),fm.params.get('latent_vec').data()

(
 [[-0.16305032]
  [-0.20041142]
  [ 0.16833992]
  [ 0.11050786]]
 <NDArray 4x1 @cpu(0)>, 
 [[-0.03649265]]
 <NDArray 1x1 @cpu(0)>, 
 [[ 0.5496404 ]
  [-0.28602466]
  [ 0.41530913]
  [ 0.26841986]]
 <NDArray 4x1 @cpu(0)>)

In [10]:
y_hat = fm.predict(X)
sum(y==y_hat)/len(y)


[1.]
<NDArray 1 @cpu(0)>

In [11]:
fm.initialize(force_reinit=True)

In [12]:
fm.collect_params()

fm0_ (
  Parameter fm0_w (shape=(4, 1), dtype=<class 'numpy.float32'>)
  Parameter fm0_b (shape=(1, 1), dtype=<class 'numpy.float32'>)
  Parameter fm0_latent_vec (shape=(4, 1), dtype=<class 'numpy.float32'>)
)

In [13]:
fm.train(X, y, max_iter = 10)

1 iter: loss is: 
[0.08071773]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.6143174]
<NDArray 1 @cpu(0)>
2 iter: loss is: 
[0.01954453]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.0611732]
<NDArray 1 @cpu(0)>
3 iter: loss is: 
[0.01027214]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00927239]
<NDArray 1 @cpu(0)>
4 iter: loss is: 
[0.00731521]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00295694]
<NDArray 1 @cpu(0)>
5 iter: loss is: 
[0.00539641]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00191879]
<NDArray 1 @cpu(0)>
6 iter: loss is: 
[0.00439355]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00100286]
<NDArray 1 @cpu(0)>
7 iter: loss is: 
[0.00363327]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00076028]
<NDArray 1 @cpu(0)>
8 iter: loss is: 
[0.00307247]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.0005608]
<NDArray 1 @cpu(0)>
9 iter: loss is: 
[0.00267749]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00039499]
<NDArray 1 @cpu(0)>
10 iter: loss is: 
[0.00237321]
<NDArray 1 @cpu(0)> loss reduction 

In [14]:
fm.params.get('w').data(),fm.params.get('b').data(),fm.params.get('latent_vec').data()

(
 [[-0.12046286]
  [-0.17704517]
  [ 0.15732752]
  [ 0.07244895]]
 <NDArray 4x1 @cpu(0)>, 
 [[-0.07127073]]
 <NDArray 1x1 @cpu(0)>, 
 [[ 0.7127195 ]
  [-0.39491937]
  [ 0.518989  ]
  [ 0.30683222]]
 <NDArray 4x1 @cpu(0)>)