In [1]:
from deepFM import DeepFM
from mxnet.gluon import nn
from mxnet import nd, autograd
import mxnet as mx
import numpy as np
from sklearn.metrics import roc_auc_score

## 准备数据

In [2]:
x1 = np.random.randint(0,500, size = (100000,1))
x2 = np.random.randint(0,1000, size = (100000,1))
x3 = np.random.randint(0,2, size = (100000,1))
x4 = np.random.randn(100000,1)
X = nd.array(np.concatenate((x1,x2,x3,x4), axis = 1))
X_onehot1 = nd.one_hot(X[:,0],depth = int(nd.max(X[:,0]).asscalar()+1))
X_onehot2 = nd.one_hot(X[:,1],depth = int(nd.max(X[:,1]).asscalar()+1))
X_onehot3 = nd.one_hot(X[:,2],depth = int(nd.max(X[:,2]).asscalar()+1))
X = nd.concat(X_onehot1,X_onehot2,X_onehot3, X[:,3].reshape(-1,1),dim = 1)

y = nd.random.shuffle(nd.concat(nd.ones((1000,1)), nd.zeros((99000,1)), dim = 0))

In [3]:
X.shape

(100000, 1503)

In [4]:
deepFM = DeepFM(n_features = 1503, f = 5, field_num = 4)

In [5]:
deepFM.initialize()

In [6]:
y_predict = deepFM.predict_prob(X)

In [7]:
roc_auc_score(y.asnumpy(), y_predict.asnumpy())

0.49313451515151513

In [8]:
deepFM.collect_params()

deepfm0_ (
  Parameter deepfm0_latent_vec (shape=(1503, 5), dtype=<class 'numpy.float32'>)
  Parameter deepfm0_w (shape=(1503, 1), dtype=<class 'numpy.float32'>)
  Parameter deepfm0_b (shape=(1, 1), dtype=<class 'numpy.float32'>)
  Parameter dense0_weight (shape=(200, 20), dtype=float32)
  Parameter dense0_bias (shape=(200,), dtype=float32)
  Parameter dense1_weight (shape=(200, 200), dtype=float32)
  Parameter dense1_bias (shape=(200,), dtype=float32)
  Parameter dense2_weight (shape=(1, 200), dtype=float32)
  Parameter dense2_bias (shape=(1,), dtype=float32)
)

In [9]:
deepFM.collect_params()['deepfm0_latent_vec'].data()


[[ 0.0068339   0.01299825  0.0301265   0.04819721  0.01438687]
 [ 0.05011239  0.00628365  0.04861524 -0.01068833  0.01729892]
 [ 0.02042518 -0.01618656 -0.00873779 -0.02834515  0.05484822]
 ...
 [-0.06364369 -0.00241996  0.03635876  0.02910428 -0.05770696]
 [ 0.0658746  -0.05029523  0.01848106  0.02461895  0.06895965]
 [ 0.06530461  0.05058237  0.04452907  0.01059669  0.05580745]]
<NDArray 1503x5 @cpu(0)>

In [10]:
deepFM.collect_params()['deepfm0_w'].data()


[[-0.00613896]
 [-0.03968295]
 [ 0.00958075]
 ...
 [ 0.06593788]
 [-0.04934957]
 [-0.01224296]]
<NDArray 1503x1 @cpu(0)>

In [11]:
deepFM.collect_params()['deepfm0_b'].data()


[[0.03896836]]
<NDArray 1x1 @cpu(0)>

In [12]:
deepFM.collect_params()['dense0_weight'].data()


[[-0.04247847  0.06293995 -0.01837847 ... -0.06219994  0.01467837
  -0.00683771]
 [ 0.0334969  -0.06720173 -0.06451371 ... -0.0396449   0.0269461
   0.00912645]
 [ 0.0093242   0.05111437 -0.03284547 ...  0.02060438  0.03028581
   0.04779406]
 ...
 [-0.06855166  0.05331292  0.03759063 ...  0.0586691  -0.04376023
   0.04661175]
 [-0.05061454 -0.02160443 -0.02231426 ...  0.06688141  0.06003698
  -0.0442403 ]
 [ 0.0166986  -0.01789841 -0.03207165 ... -0.05084866  0.0428737
  -0.028384  ]]
<NDArray 200x20 @cpu(0)>

In [13]:
deepFM.collect_params()['dense0_bias'].data()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
<NDArray 200 @cpu(0)>

In [15]:
deepFM.train(X, y, max_iter = 100, batchsize = 10000)

1 iter: loss is: 
[0.45802754]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.2587399]
<NDArray 1 @cpu(0)>
2 iter: loss is: 
[0.35046375]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.10756379]
<NDArray 1 @cpu(0)>
3 iter: loss is: 
[0.28638947]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.06407428]
<NDArray 1 @cpu(0)>
4 iter: loss is: 
[0.24366297]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.0427265]
<NDArray 1 @cpu(0)>
5 iter: loss is: 
[0.21318641]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.03047656]
<NDArray 1 @cpu(0)>
6 iter: loss is: 
[0.19040512]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.0227813]
<NDArray 1 @cpu(0)>
7 iter: loss is: 
[0.17276779]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.01763733]
<NDArray 1 @cpu(0)>
8 iter: loss is: 
[0.15874]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.01402779]
<NDArray 1 @cpu(0)>
9 iter: loss is: 
[0.14733823]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.01140177]
<NDArray 1 @cpu(0)>
10 iter: loss is: 
[0.13790663]
<NDArray 1 @cpu(0)> loss reduction is:

80 iter: loss is: 
[0.05964261]
<NDArray 1 @cpu(0)> loss reduction is: 
[0.00010175]
<NDArray 1 @cpu(0)>
81 iter: loss is: 
[0.05954418]
<NDArray 1 @cpu(0)> loss reduction is: 
[9.8433346e-05]
<NDArray 1 @cpu(0)>
82 iter: loss is: 
[0.05944897]
<NDArray 1 @cpu(0)> loss reduction is: 
[9.5207244e-05]
<NDArray 1 @cpu(0)>
83 iter: loss is: 
[0.05935684]
<NDArray 1 @cpu(0)> loss reduction is: 
[9.212643e-05]
<NDArray 1 @cpu(0)>
84 iter: loss is: 
[0.05926765]
<NDArray 1 @cpu(0)> loss reduction is: 
[8.9194626e-05]
<NDArray 1 @cpu(0)>
85 iter: loss is: 
[0.0591813]
<NDArray 1 @cpu(0)> loss reduction is: 
[8.635223e-05]
<NDArray 1 @cpu(0)>
86 iter: loss is: 
[0.05909765]
<NDArray 1 @cpu(0)> loss reduction is: 
[8.364767e-05]
<NDArray 1 @cpu(0)>
87 iter: loss is: 
[0.05901663]
<NDArray 1 @cpu(0)> loss reduction is: 
[8.101761e-05]
<NDArray 1 @cpu(0)>
88 iter: loss is: 
[0.05893812]
<NDArray 1 @cpu(0)> loss reduction is: 
[7.851422e-05]
<NDArray 1 @cpu(0)>
89 iter: loss is: 
[0.058862]
<NDArra

In [16]:
y_predict = deepFM.predict_prob(X)

In [17]:
roc_auc_score(y.asnumpy(), y_predict.asnumpy())

0.540634702020202

In [18]:
deepFM.collect_params()['deepfm0_latent_vec'].data()


[[-0. -0.  0.  0. -0.]
 [ 0. -0.  0.  0.  0.]
 [ 0. -0.  0.  0.  0.]
 ...
 [-0.  0. -0.  0.  0.]
 [-0.  0. -0.  0. -0.]
 [ 0. -0. -0.  0. -0.]]
<NDArray 1503x5 @cpu(0)>

In [19]:
deepFM.collect_params()['deepfm0_w'].data()


[[-0.00884028]
 [-0.00743944]
 [-0.00949604]
 ...
 [-1.0749024 ]
 [-1.0844254 ]
 [ 0.02083395]]
<NDArray 1503x1 @cpu(0)>

In [20]:
deepFM.collect_params()['deepfm0_b'].data()


[[-1.440484]]
<NDArray 1x1 @cpu(0)>

In [25]:
deepFM.collect_params()['dense0_weight'].data()


[[ 0. -0.  0. ... -0. -0. -0.]
 [ 0. -0. -0. ...  0.  0.  0.]
 [-0. -0.  0. ... -0. -0. -0.]
 ...
 [ 0. -0. -0. ... -0. -0. -0.]
 [ 0.  0. -0. ...  0.  0.  0.]
 [ 0. -0.  0. ...  0.  0.  0.]]
<NDArray 200x20 @cpu(0)>

In [26]:
deepFM.collect_params()['dense0_bias'].data()


[-0.0000000e+00  0.0000000e+00 -0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00 -0.0000000e+00
 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00 -0.0000000e+00 -0.0000000e+00
 -0.0000000e+00 -0.0000000e+00  0.0000000e+00 -0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
 -0.0000000e+00  0.0000000e+00  0.0000000e+00 -0.0000000e+00
  0.0000000e+00 -0.0000000e+00  0.0000000e+00 -0.0000000e+00
  0.0000000e+00 -0.0000000e+00 -0.0000000e+00 -3.3192331e-04
  0.0000000e+00 -5.5271994e-06 -0.0000000e+00 -0.0000000e+00
  0.0000000e+00 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00
  0.0000000e+00 -0.0000000e+00 -0.0000000e+00  0.0000000e+00
  0.0000000e+00 -0.0000000e+00 -0.0000000e+00  0.0000000e+00
  0.0000000e+00 -0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
 -0.0000000e+00 -0.0000000e+00  0.0000000e+00 -0.0000000e+00
  8.5694285e-04  0.0000